baseURL = "https://docs.librepcb.org/"
languageCode = "en-us"
title = "LibrePCB User Guide"
theme = "learn"

[params]
  themeVariant = "green"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
