language: ruby
notifications:
  email:
    on_success: change
    on_failure: change

script:
  - ./ci/stylecheck.sh                                || travis_terminate 1
  - ./ci/build.sh                                     || travis_terminate 1
  - ./ci/upload_artifacts.sh                          || travis_terminate 1
