= Installation
:appimage-filename: librepcb-cli-{version}-linux-x86_64.AppImage
:appimage-url: {releases-url}/{appimage-filename}
:bundle-filename: librepcb-cli-{version}-mac-x86_64.dmg
:bundle-url: {releases-url}/{bundle-filename}
:bundle-arm64-filename: librepcb-cli-{version}-mac-arm64.dmg
:bundle-arm64-url: {releases-url}/{bundle-arm64-filename}

== Binary Releases

Our official LibrePCB xref:installation:index.adoc[binary releases] contain
the `librepcb-cli` executable next to the GUI application, so usually no
separate installation is needed. But there are two exceptions: The AppImage
and the macOS bundle.

=== Linux AppImage

*Download {appimage-url}[{appimage-filename}], make it executable and run it:*

[source,bash,subs="attributes"]
----
wget "{appimage-url}"
chmod +x ./{appimage-filename}
./{appimage-filename}
----

=== macOS Bundle

Download the portable `*.dmg` file matching your CPU architecture:

* *Intel (x86_64)*: {bundle-url}[{bundle-filename}]
* *Apple Silicon (arm64)*: {bundle-arm64-url}[{bundle-arm64-filename}]

Double-click the downloaded file in Finder. Then drag and drop the app
onto the "Applications" folder in Finder.

== Docker Image

The easiest way to get the LibrePCB CLI on Linux (especially for usage on CI)
is to pull our official Docker image
https://hub.docker.com/r/librepcb/librepcb-cli[librepcb/librepcb-cli]:

[source,bash,subs="attributes"]
----
docker run -it --rm -v `pwd`:/work -u `id -u`:`id -g` \
    librepcb/librepcb-cli:{version} --help
----
