[#gettingstarted-installation]
=== Installation

.Attention: Unstable file format!
[IMPORTANT]
====
The file format of LibrePCB is still under development, and breaking changes
can occur at any time. This means that you may (or *will*) not be able to
open your created libraries and projects with future versions of LibrePCB!

Or in other words: LibrePCB does not yet have an upgrade mechanism for the
files created with older LibrePCB versions. We will start providing an upgrade
mechanism as soon as we publish the first stable release of LibrePCB.
====


==== Download & Start LibrePCB

.No stable releases
[NOTE]
====
There are not yet any stable releases available, so at the moment you need to
download the nightly builds instead.
====

===== Windows
:zip-filename: librepcb-nightly-windows-x86.zip
:zip-url: https://download.librepcb.org/nightly_builds/master/librepcb-nightly-windows-x86.zip

Download {zip-url}[{zip-filename}] and extract its content. Then double-click
the contained file `bin\librepcb.exe` to run the application.

===== Linux
:appimage-filename: librepcb-nightly-linux-x86_64.AppImage
:appimage-url: https://download.librepcb.org/nightly_builds/master/librepcb-nightly-linux-x86_64.AppImage

Download {appimage-url}[{appimage-filename}], make it executable and start it:

[source,bash,subs="attributes"]
----
wget "{appimage-url}"
chmod +x ./{appimage-filename}
./{appimage-filename}
----

===== Mac
:dmg-filename: librepcb-nightly-mac-x86_64.dmg
:dmg-url: https://download.librepcb.org/nightly_builds/master/librepcb-nightly-mac-x86_64.dmg

Download {dmg-url}[{dmg-filename}] and double-click it. Then drag and drop the
app onto the "Applications" icon of Finder.
