[#gettingstarted-installation]
=== Installation

[NOTE]
====
There are not yet any stable releases available, so at the moment you need to
download the nightly builds instead.
====

.Attention: Unstable file format!
[IMPORTANT]
====
The file format of LibrePCB is still under development, and breaking changes
can occur at any time. This means that you may not be able to open your
created libraries and projects with future versions of LibrePCB!

Or in other words: LibrePCB does not yet have an upgrade mechanism for the
files created with older LibrePCB versions. We will start providing an upgrade
mechanism as soon as we publish the first stable release of LibrePCB.
====

==== Method 1: Installer

The recommended way to install LibrePCB is to use the online installer.
It provides the following features:

- Downloads the latest version from the Internet (no offline installation
  possible).
- Installs a maintenance tool to easily download and install updates.
- Creates start menu entries for LibrePCB and the maintenance tool.
- Optionally registers `*.lpp` files, so LibrePCB projects can be opened
  with a double-click in the file manager.

[discrete]
===== Windows
:windows-installer-filename: librepcb-installer-nightly-windows-x86.exe
:windows-installer-url: https://download.librepcb.org/nightly_builds/master/librepcb-installer-nightly-windows-x86.exe

Download and run {windows-installer-url}[{windows-installer-filename}].

[discrete]
===== Linux
:linux-installer-filename: librepcb-installer-nightly-linux-x86_64.run
:linux-installer-url: https://download.librepcb.org/nightly_builds/master/librepcb-installer-nightly-linux-x86_64.run

Download {linux-installer-url}[{linux-installer-filename}], make it executable
and run it:

[source,bash,subs="attributes"]
----
wget "{linux-installer-url}"
chmod +x ./{linux-installer-filename}
./{linux-installer-filename}
----

[discrete]
===== Mac
:mac-installer-filename: librepcb-installer-nightly-mac-x86_64.dmg
:mac-installer-url: https://download.librepcb.org/nightly_builds/master/librepcb-installer-nightly-mac-x86_64.dmg

Download and run {mac-installer-url}[{mac-installer-filename}]. "Unverified" packages may have to be opened via right-click.

[IMPORTANT]
====
Because Apple doesn't provide the ability to run macOS without purchasing their
hardware, we're not able to automatically test LibrePCB for macOS. Feel free to
https://github.com/LibrePCB/LibrePCB/issues[open an issue] if LibrePCB doesn't
work as expected.
====

==== Method 2: Portable Package

Alternatively you could run LibrePCB without installing it. But then you don't
get an update mechanism, no start menu entries are created, and `*.lpp` files
will not be registered.

[discrete]
===== Windows
:windows-zip-filename: librepcb-nightly-windows-x86.zip
:windows-zip-url: https://download.librepcb.org/nightly_builds/master/librepcb-nightly-windows-x86.zip

Download and extract {windows-zip-url}[{windows-zip-filename}], then
run the contained file `bin\librepcb.exe`.

[discrete]
===== Linux
:linux-appimage-filename: librepcb-nightly-linux-x86_64.AppImage
:linux-appimage-url: https://download.librepcb.org/nightly_builds/master/librepcb-nightly-linux-x86_64.AppImage

Download {linux-appimage-url}[{linux-appimage-filename}], make it executable
and start it:

[source,bash,subs="attributes"]
----
wget "{linux-appimage-url}"
chmod +x ./{linux-appimage-filename}
./{linux-appimage-filename}
----

[discrete]
===== Mac
:dmg-filename: librepcb-nightly-mac-x86_64.dmg
:dmg-url: https://download.librepcb.org/nightly_builds/master/librepcb-nightly-mac-x86_64.dmg

Download {dmg-url}[{dmg-filename}] and double-click it. Then drag and drop the
app onto the "Applications" icon of Finder.

[IMPORTANT]
====
Because Apple doesn't provide the ability to run macOS without purchasing their
hardware, we're not able to automatically test LibrePCB for macOS. Feel free to
https://github.com/LibrePCB/LibrePCB/issues[open an issue] if LibrePCB doesn't
work as expected.
====
