[#gettingstarted-installation]
=== Installation

.Disclaimer
[WARNING]
====
Please note that LibrePCB is a very early software and thus
isn't as mature as other EDA tools. Use LibrePCB at your own risk,
accepting that we don't take responsibility for any issues caused
by software bugs or other reasons. For details, please read the full
https://github.com/LibrePCB/LibrePCB/blob/master/LICENSE.txt[license text].
====

.Note for macOS users
[NOTE]
====
Because Apple doesn't provide the ability to run macOS without purchasing their
hardware, we're not able to test LibrePCB on macOS. Don't hesitate to
https://github.com/LibrePCB/LibrePCB/issues[open an issue] if LibrePCB doesn't
work as expected.
====

==== Online Installer

The recommended way to install LibrePCB is to use the online installer.
It provides the following features:

- Downloads the latest version from the Internet (no offline installation
  possible).
- Installs a maintenance tool to easily download and install updates.
- Creates start menu entries for LibrePCB and the maintenance tool.
- Optionally registers `*.lpp` files, so LibrePCB projects can be opened
  with a double-click in the file manager.

[discrete]
===== Windows
:windows-installer-filename: librepcb-installer-{version}-windows-x86.exe
:windows-installer-url: {releases_url}/{windows-installer-filename}

Download and run {windows-installer-url}[{windows-installer-filename}].

[discrete]
===== Linux
:linux-installer-filename: librepcb-installer-{version}-linux-x86_64.run
:linux-installer-url: {releases_url}/{linux-installer-filename}

Download {linux-installer-url}[{linux-installer-filename}], make it executable
and run it:

[source,bash,subs="attributes"]
----
wget "{linux-installer-url}"
chmod +x ./{linux-installer-filename}
./{linux-installer-filename}
----

[discrete]
===== Mac
:mac-installer-filename: librepcb-installer-{version}-mac-x86_64.dmg
:mac-installer-url: {releases_url}/{mac-installer-filename}

Download and run {mac-installer-url}[{mac-installer-filename}]. "Unverified" packages may have to be opened via right-click.

==== Portable Package

Alternatively you could run LibrePCB without installing it. But then you don't
get an update mechanism, no start menu entries are created, and `*.lpp` files
will not be registered.

[discrete]
===== Windows
:windows-zip-filename: librepcb-{version}-windows-x86.zip
:windows-zip-url: {releases_url}/{windows-zip-filename}

Download and extract {windows-zip-url}[{windows-zip-filename}], then
run the contained file `bin\librepcb.exe`.

[discrete]
===== Linux
:linux-appimage-filename: librepcb-{version}-linux-x86_64.AppImage
:linux-appimage-url: {releases_url}/{linux-appimage-filename}

Download {linux-appimage-url}[{linux-appimage-filename}], make it executable
and start it:

[source,bash,subs="attributes"]
----
wget "{linux-appimage-url}"
chmod +x ./{linux-appimage-filename}
./{linux-appimage-filename}
----

[discrete]
===== Mac
:mac-bundle-filename: librepcb-{version}-mac-x86_64.dmg
:mac-bundle-url: {releases_url}/{mac-bundle-filename}

Download {mac-bundle-url}[{mac-bundle-filename}] and double-click it.
Then drag and drop the app onto the "Applications" icon of Finder.
