[#cli-installation]
= Installation

[discrete]
== Online Installer

If you have installed LibrePCB with the installer (as described
<<gettingstarted-installation,here>>), you should already have the
`librepcb-cli` tool available in the installation directory.

[discrete]
== Portable Package

Alternatively you could run `librepcb-cli` without installing it.

[discrete]
=== Windows
:windows-zip-filename: librepcb-{version}-windows-x86.zip
:windows-zip-url: {releases_url}/{windows-zip-filename}

Download and extract {windows-zip-url}[{windows-zip-filename}], then
run the contained file `bin\librepcb-cli.exe`.

[discrete]
=== Linux
:linux-appimage-filename: librepcb-cli-{version}-linux-x86_64.AppImage
:linux-appimage-url: {releases_url}/{linux-appimage-filename}
:linux-targz-foldername: librepcb-{version}-linux-x86_64
:linux-targz-filename: librepcb-{version}-linux-x86_64.tar.gz
:linux-targz-url: {releases_url}/{linux-targz-filename}
:linux-docker-name: librepcb/librepcb-cli
:linux-docker-tag: {linux-docker-name}:{version}
:linux-docker-url: https://hub.docker.com/r/{linux-docker-name}

[discrete]
==== AppImage

Download {linux-appimage-url}[{linux-appimage-filename}], make it executable
and start it:

[source,bash,subs="attributes"]
----
wget "{linux-appimage-url}"
chmod +x ./{linux-appimage-filename}
./{linux-appimage-filename}
----

[discrete]
==== Binaries

Alternatively, you can download and extract
{linux-targz-url}[{linux-targz-filename}] which contains the `librepcb-cli`
executable:

[source,bash,subs="attributes"]
----
wget "{linux-targz-url}"
tar -xvzf ./{linux-targz-filename}
./{linux-targz-foldername}/bin/librepcb-cli
----

[discrete]
==== Docker

Or if you have https://www.docker.com/[Docker] installed, you can use our
official image {linux-docker-url}[`{linux-docker-name}`]:

[source,bash,subs="attributes"]
----
docker run -it --rm -u $(id -u):$(id -g) -v `pwd`:/work {linux-docker-tag}
----

[discrete]
=== Mac
:mac-bundle-filename: librepcb-cli-{version}-mac-x86_64.dmg
:mac-bundle-url: {releases_url}/{mac-bundle-filename}

Download {mac-bundle-url}[{mac-bundle-filename}] and double-click it. Then drag
and drop the app onto the "Applications" icon of Finder.
