---
title: About LibrePCB
weight: 10
---

== Features

* Cross-platform (Unix/Linux, Mac OS X, Windows)
* All-In-One: project management + library/schematic/board editors
* Intuitive, modern and easy-to-use graphical user interface
* Very powerful library design with some innovative concepts
* Human-readable file formats for both libraries and projects
* Multi-PCB feature (different PCB variants of the same schematic)
* Automatic netlist synchronisation between schematic and board


[#projectstatus]
== Project Status

LibrePCB is still under development and many features are not
implemented yet. So here's an overview about the project status:

[discrete]
=== What's working

* Downloading, creating and modifying libraries
* Drawing simple schematics with multiple sheets (incl. print or PDF export)
* Creating simple multilayer PCBs (incl. DRC and Gerber/Excellon/PDF export)
* Exporting bill of materials (BOM)

[discrete]
=== What's missing

* No hierarchical schematics
  https://github.com/LibrePCB/LibrePCB/wiki/Wishlist#schematic-editor[[wishlist\]]
* No buses in schematics
  https://github.com/LibrePCB/LibrePCB/wiki/Wishlist#schematic-editor[[wishlist\]]
* No 3D board viewer
  https://github.com/LibrePCB/LibrePCB/wiki/Wishlist#board-editor[[wishlist\]]
* No clipboard functionality (cut/copy/paste) in board/schematic editors
  https://github.com/LibrePCB/LibrePCB/issues/13[[#13\]]

Of course all these features will be implemented in future. Please consider to
https://github.com/LibrePCB/LibrePCB/blob/master/CONTRIBUTING.md[contribute]
or https://www.patreon.com/librepcb[donate] to support the development of
LibrePCB!
