= Installation on Linux
:appimage-filename: librepcb-{version}-linux-x86_64.AppImage
:appimage-url: {releases-url}/{appimage-filename}

Due to the diversity of the Linux ecosystem, there are many different ways
to install LibrePCB. The order of the options provided below do not reflect
any recommendation.

[TIP]
====
If you're unsure, here our recommendations:

* On Ubuntu: <<snap>>
* On a Raspberry Pi: <<flatpak>>
* Everywhere else: <<appimage>>
====

[#appimage,reftext=Portable AppImage]
== Portable AppImage (x86_64)

The AppImage is a single-file portable package which runs on most Linux
distributions. It is fully functional without installing anything on your
system, but it does not provide an update mechanism.

*Download {appimage-url}[{appimage-filename}], make it executable and run it:*

[source,bash,subs="attributes"]
----
wget "{appimage-url}"
chmod +x ./{appimage-filename}
./{appimage-filename}
----

If you're not familiar with the terminal: Right-click on the downloaded file
and then check something like _Allow executing file as program_ or
_Run as executable_. Afterwards double-click the file to run it.

[#snap,reftext=Snap Package]
== Snap Package (multi-arch)

For distrubutions like Ubuntu which use the https://snapcraft.io/[Snap]
package manager, probably the easiest way is to install the
https://snapcraft.io/librepcb[LibrePCB Snap package].

On Ubuntu, just open the _Ubuntu Software_ application (app store),
search for LibrePCB and install it. Alternatively, run this command from
in the terminal:

[source,bash]
----
sudo snap install librepcb
----

[NOTE]
====
Some users https://github.com/LibrePCB/LibrePCB/issues/989[reported]
that LibrePCB crashes when installed as a Snap package. It seems to be a
problem related to fonts and Snap. If you experience this issue, the
following workaround might help:

[source,bash]
----
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r
----
====

For more information about Snap, check out
https://snapcraft.io/docs[its documentation].

[#flatpak,reftext=Flatpak]
== FlatPak (multi-arch)

LibrePCB is also available as a https://flatpak.org[FlatPak] package from
https://flathub.org/apps/details/org.librepcb.LibrePCB[FlatHub]. Assuming you
have followed https://flatpak.org/setup/[FlatPak setup], you can configure
FlatHub and install LibrePCB as follows:

[IMPORTANT]
====
After installing FlatPak, make sure to **reboot the computer** before executing
the follwing commands! Otherwise LibrePCB might not appear in your application
launcher.
====

[source,bash,subs="attributes"]
----
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub org.librepcb.LibrePCB
----

// Keep this section just for some time to keep the links working and to
// inform users about the change.
[#installer,reftext=Online Installer]
== Online Installer (abandoned)

Note that starting with LibrePCB 1.0, we do no longer provide an installer for
Linux. If you installed a previous LibrePCB release with the installer,
please uninstall it with the _LibrePCB Maintenance Tool_ and install the
latest release with a different installation method instead.
