= Installation on macOS
:bundle-filename: librepcb-{version}-mac-x86_64.dmg
:bundle-url: {releases-url}/{bundle-filename}
:bundle-arm64-filename: librepcb-{version}-mac-arm64.dmg
:bundle-arm64-url: {releases-url}/{bundle-arm64-filename}

== Portable Package

To install LibrePCB, download the portable `*.dmg` file matching your
CPU architecture:

* *Intel (x86_64)*: {bundle-url}[{bundle-filename}]
* *Apple Silicon (arm64)*: {bundle-arm64-url}[{bundle-arm64-filename}]

Double-click the downloaded file in Finder. Then drag and drop the LibrePCB
app onto the "Applications" folder in Finder. Afterwards you'll find
LibrePCB in the Launchpad.

[IMPORTANT]
====
Unfortunately we're not able (yet) to officially sign the macOS binary.
Therefore macOS refuses to start LibrePCB by default. As a workaround,
you need to run it once with menu:Right-click[Open] on the LibrePCB
application in the Launchpad. If this doesn't work, try it a second time.

Afterwards you should be able to run LibrePCB normally with a single click.
====

// Keep this section just for some time to keep the links working and to
// inform users about the change.
[#online-installer,reftext=Online Installer]
== Online Installer (abandoned)

Note that starting with LibrePCB 1.0, we do no longer provide an installer for
macOS. If you installed a previous LibrePCB release with the installer,
please uninstall it with the _LibrePCB Maintenance Tool_ and install the
latest release with the <<portable-package>> instead.
