= Installation on Windows
:installer-filename: librepcb-installer-{version}-windows-x86.exe
:installer-url: {releases-url}/{installer-filename}
:zip-filename: librepcb-{version}-windows-x86.zip
:zip-url: {releases-url}/{zip-filename}

== Online Installer

The recommended way to install LibrePCB is to use the online installer.
It provides the following features:

- Installs a maintenance tool to easily download and install updates.
- Creates start menu entries for LibrePCB and the maintenance tool.
- Optionally registers `*.lpp` files, so LibrePCB projects can be opened
  with a double-click in the file manager.

*Just download and run {installer-url}[{installer-filename}].*
Afterwards you'll find LibrePCB in your start menu.

== Portable Package

Alternatively you could run LibrePCB without installing it. But then you don't
get an update mechanism, no start menu entries are created, and `*.lpp` files
will not be registered.

Download and extract {zip-url}[{zip-filename}], then run the contained file
`bin\librepcb.exe`.
