= Troubleshooting

In case you encounter any problems with LibrePCB, this chapter gives you some
tips to get them solved or to get help from the community.

[#there-is-no-element-of-type]
== Error: There is no element of type 'X' with the UUID 'Y'

Whenever an error message pops up with a message like
_There is no element of type 'X' with the UUID 'Y'_ or something like
_Element with UUID 'X' not found_, it is very very very likely that you made
some xref:user-manual:references.adoc#breaking-changes[breaking change] in a library
element. Those errors then occur either in the component- or device editor,
or after updating the project library with the _Project Library Updater_.

Since these are complex issues, the correct solution depends on a case-by-case
basis. All we can give here are some general recommendations:

. Read xref:user-manual:references.adoc[] until you understand it.
. From now on, follow the
  xref:user-manual:references.adoc#recommendations[recommendations]
  on that page to avoid running into this problem again in future.
. If you have any idea in _which_ of the library elements you (recently) made
  breaking changes, delete them completely. It may hurt, but it's often the
  only way out of the mess. You may want to back up the library elements before
  deletion -- use the menu:Device[Show in File Manager] menu item to locate the
  directory to back up.
. If the project library update still fails after deleting the suspicious
  library elements, you may need to remove the suspicious elements also from
  the schematics & boards, and then re-add them the normal way with the
  _Add Component_ dialog.
. In important/urgent cases, you may ask LibrePCB developers for help. However,
  we kindly ask for a donation as a compensation for our invested time.

== Project Library Update Fails

See <<there-is-no-element-of-type>>.

== Workspace Sync (Dropbox, Cloud, Git, ...)

If you sync your LibrePCB workspace with a cloud or similar, it's important to
follow some rules to avoid problems:

* Exclude all files with pattern `cache_*` from the synchronization. These
  files are stored in the workspace subdirectory `data/libraries/`. If
  LibrePCB does not work correctly and you had these files synced, delete
  those files manually (while LibrePCB is closed) and try again. These files
  are automatically recreated after deletion.
* Consider excluding files named `.lock` from the synchronization too if you
  experience problems with file locks. However, never open a project or
  library at the same time from multiple computers!
* Hidden files ("dotfiles") must be synchronized. If hidden files are
  ignored by the sync, LibrePCB will not work correctly.

Note that even when following these rules, it's still not guaranteed that
everything works correctly. Especially with clouds the problem is that they
are not operating "atomically", which can cause very serious troubles.
Therefore we do not recommend to store any LibrePCB files in a cloud.

Working with a version control system like Git however is fine, since it works
atomically and even allows to roll back a change in the very unlikely case
something is messed up. We just recommend to use version control per-project
and per-library, not for the whole workspace.

== Wayland

There are some known issues when using LibrePCB natively on Wayland. If you
experience any problems, please try XWayland or X11 (both should work fine).

== Slow/Laggy UI

On some systems, especially with large projects, the UI could get a bit
laggy. We are aware of this and try to improve it. In the mean time, try the
following things:

* Reduce grid density or disable grid completely
* Avoid huge schematics -- split them into multiple sheets (e.g. DIN A4 format)
* In the schematic editor, hide pin numbers (toggle menu:View[Show Pin Numbers])
* In the board editor, reduce the number of visible layers
* Enable or disable OpenGL in workspace settings (test both modes)
* If using a high-resolution display, try to reduce resolution
* On a laptop, plug in the charger :-)
